services:
  linkshelf:
    image: linkshelf6
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8082:8080"
    environment:
      - APP_DATABASE_HOST=postgres
    volumes:
      - ./backend/config.default.yaml:/app/config.default.yaml
    depends_on:
      - postgres