name: Build Docker Image

# https://gist.github.com/seunggabi/87f8c722d35cd07deb3f649d45a31082

on:
  push:
    branches:
      - main
      - develop
      - 'develop/**'
      - 'feat/**'
      - 'chore/**'
      - 'docs/**'
      - 'fix/**'
      - 'refactor/**'
      - 'style/**'
      - 'test/**'

env:
  IMAGE_NAME: linkshelf

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - name: Build image
        run: docker build . --file ./.docker/Containerfile --tag $IMAGE_NAME