name: CI â€“ Build, Test & Coverage

on:
  push:
    branches:
      - main
      - develop
      - 'develop/**'
      - 'feat/**'
      - 'chore/**'
      - 'docs/**'
      - 'fix/**'
      - 'refactor/**'
      - 'style/**'
      - 'test/**'
  pull_request:

env:
  IMAGE_NAME: linkshelf

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true

      - name: Install mockgen
        run: |
          go install go.uber.org/mock/mockgen@latest

      - name: Build
        working-directory: backend
        run: |
          go build ./...

      - name: Verify go generate is up-to-date
        working-directory: backend
        run: |
          go generate ./...
          git diff --exit-code

      - name: Run unit tests
        working-directory: backend
        run: |
          go test ./...

      - name: Run integration tests
        working-directory: backend
        run: |
          go test -tags=integration ./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: backend/coverage.out
          threshold-total: 0 # if you want to enforce a minimum coverage, set it here
          debug: true

          # push badge only when allowed (no fork PRs)
          git-token: ${{ (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && secrets.GITHUB_TOKEN || '' }}

          # store badge on the SAME branch as the pipeline
          git-branch: ${{ github.ref_name }}
