name: Release â€“ Build & Push Docker Image

on:
  release:
    types: [created]

env:
  IMAGE_NAME: linkshelf
  IMAGE_TAG: ${{ github.event.release.tag_name }}
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -f .docker/Containerfile \
            -t $IMAGE_NAME \
            --build-arg IMAGE_NAME=$IMAGE_NAME \
            --build-arg IMAGE_TAG=$IMAGE_TAG \
            --label org.opencontainers.image.version=$IMAGE_TAG \
            .

      - name: Tag image
        run: |
          docker tag \
            $IMAGE_NAME \
            $REGISTRY/$OWNER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push image
        run: |
          docker push $REGISTRY/$OWNER/$IMAGE_NAME:$IMAGE_TAG

      - name: Tag latest
        run: |
          docker tag \
            $IMAGE_NAME \
            $REGISTRY/$OWNER/$IMAGE_NAME:latest

      - name: Push latest
        run: |
          docker push $REGISTRY/$OWNER/$IMAGE_NAME:latest
  coverage:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Run tests with coverage
        working-directory: backend
        run: |
          go test ./... -coverprofile=coverage.out

      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-go@v3
        with:
          filename: backend/coverage.out

      - name: Commit coverage badge
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update coverage badge"
          add: "README.md"
